
exclude: versions.*|env.py|chalicelib/common|tests/data
default_language_version:
  python: python39
repos:
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: poetry run autoflake --in-place --remove-all-unused-imports -r --ignore-init-module-imports
        language: system
        types: [python]

      - id: isort
        name: isort
        entry: poetry run isort -j 5
        language: system
        types: [python]

      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]

      - id: pylint
        name: pylint
        exclude: ^tests/
        entry: poetry run pylint -j 0
        language: system
        types: [python]

      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [python]

      - id: export-requirements
        name: Export requeriments.txt
        language: system
        entry: poetry export --without-hashes -o requirements.txt
        pass_filenames: false
        files: ^(pyproject.toml|poetry.lock)$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        # exclude autogenerated files
        exclude: /README\.rst$|\.pot?$
      - id: end-of-file-fixer
        # exclude autogenerated files
        exclude: /README\.rst$|\.pot?$
      - id: debug-statements
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
        # exclude files where underlines are not distinguishable from merge conflicts
        exclude: /README\.rst$|^docs/.*\.rst$
      - id: check-symlinks
      - id: check-xml
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
      - id: pyupgrade
